/* A.R.T shared access layer. Identity/entitlement only; media/analysis remain local. */
(()=>{'use strict';
const cfg=window.AMC_ACCESS_CONFIG||{},familyId=cfg.familyId||'acoustic',productId=cfg.productId||'tool',family=cfg.families?.[familyId]||{},product=family.products?.[productId]||{label:productId,maxDevices:2,enabled:true},legal=cfg.legal||{},fb=window.AMC_FIREBASE_CONFIG||{},configured=Boolean(fb.apiKey&&fb.authDomain&&fb.projectId&&fb.appId),state={configured,familyId,productId,family,product,user:null,profile:null,access:null};
const deviceKey='art_device_id_v1',visitorKey='amct_visitor_id_v1',visitSentKey='amct_visit_sent_v1';
function visitorId(){let id=localStorage.getItem(visitorKey);if(!id){id=crypto.randomUUID?crypto.randomUUID():'visit-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(visitorKey,id)}return id}
function acquisitionSource(){const q=new URLSearchParams(location.search),u=(q.get('utm_source')||'').toLowerCase(),r=(document.referrer||'').toLowerCase();if(u==='x'||u==='twitter'||r.includes('x.com')||r.includes('twitter.com')||r.includes('t.co'))return'x';if(u==='note'||r.includes('note.com'))return'note';if(!r)return'direct';return'other'}
async function analyticsWrite(fields,{initial=false}={}){if(!configured||!window.firebase?.apps)return;try{if(!firebase.apps.length)firebase.initializeApp(fb);const ref=firebase.firestore().collection('analytics_visits').doc(visitorId()),now=firebase.firestore.FieldValue.serverTimestamp();await ref.set(initial?{source:acquisitionSource(),visitedAt:now}:{...fields},{merge:!initial});}catch(e){console.warn('Acquisition analytics unavailable',e)}}
async function trackVisit(){if(localStorage.getItem(visitSentKey))return;await analyticsWrite({}, {initial:true});localStorage.setItem(visitSentKey,'1')}
async function trackSignupView(){await analyticsWrite({signupViewAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function trackSignup(){await analyticsWrite({signupAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function trackToolStart(){await analyticsWrite({toolStartedAt:firebase.firestore.FieldValue.serverTimestamp()})}
function deviceId(){let id=localStorage.getItem(deviceKey);if(!id){id=crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(deviceKey,id)}return id}function dispatch(n,d={}){window.dispatchEvent(new CustomEvent(n,{detail:d}))}function status(){return{...state,deviceId:deviceId(),maxDevices:product.maxDevices||2}}function access(data){return data.families?.[familyId]?.products?.[productId]||{state:'active',devices:{}}}function familyState(data){return data.families?.[familyId]?.state||'active'}function legalAccepted(data){return data.legal?.termsVersion===legal.termsVersion&&data.legal?.privacyVersion===legal.privacyVersion}
async function start(){void trackVisit();if(!configured){dispatch('amc-access-ready',status());return status()}if(!window.firebase?.apps)throw new Error('Firebase SDK is not loaded.');if(!firebase.apps.length)firebase.initializeApp(fb);const auth=firebase.auth(),db=firebase.firestore();await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);return new Promise(resolve=>auth.onAuthStateChanged(async user=>{state.user=user||null;state.profile=null;state.access=null;if(user){const ref=db.collection('users').doc(user.uid),snap=await ref.get(),data=snap.exists?snap.data():{},global=data.accountState||'active',group=familyState(data),a=access(data),ps=a.state||'active';state.profile=data;state.access=a;if([global,group,ps].some(x=>x==='banned'||x==='suspended')||family.enabled===false||product.enabled===false){dispatch('amc-access-blocked',status());resolve(status());return}if(!legalAccepted(data)){dispatch('amc-legal-required',{...status(),termsVersion:legal.termsVersion,privacyVersion:legal.privacyVersion});resolve(status());return}const devices={...(a.devices||{})},id=deviceId(),max=product.maxDevices||2;if(!devices[id]){const active=Object.values(devices).filter(v=>!v?.revoked).length;if(active>=max){state.access={...a,devices};dispatch('amc-device-limit',status());resolve(status());return}state.access={...a,devices};dispatch('amc-device-name-required',{...status(),suggestedName:'iPhone '+(active+1)});resolve(status());return}else devices[id].lastSeenAt=firebase.firestore.FieldValue.serverTimestamp();await ref.set({email:user.email||'',accountState:global,families:{[familyId]:{state:group,products:{[productId]:{...a,state:ps,devices,lastSeenAt:firebase.firestore.FieldValue.serverTimestamp()}}}},lastSeenAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});state.access={...a,state:ps,devices}}dispatch('amc-access-ready',status());resolve(status())},err=>{dispatch('amc-access-error',{message:err.message});resolve(status())}))}
async function acceptLegal(){if(!state.user)throw new Error('Authentication required.');const db=firebase.firestore(),ref=db.collection('users').doc(state.user.uid),snap=await ref.get(),data=snap.data()||{},now=firebase.firestore.FieldValue.serverTimestamp(),a=access(data),group=familyState(data),ps=a.state||'active';await ref.set({email:state.user.email||'',accountState:data.accountState||'active',families:{[familyId]:{state:group,products:{[productId]:{...a,state:ps,devices:a.devices||{}}}}},legal:{termsVersion:legal.termsVersion||'',privacyVersion:legal.privacyVersion||'',agreedAt:now},updatedAt:now},{merge:true});state.profile={...data,email:state.user.email||'',accountState:data.accountState||'active',legal:{termsVersion:legal.termsVersion||'',privacyVersion:legal.privacyVersion||'',agreedAt:now}};state.access={...a,state:ps,devices:a.devices||{}};return status()}
async function registerDevice(name){if(!state.user)throw new Error('Authentication required.');const db=firebase.firestore(),ref=db.collection('users').doc(state.user.uid),snap=await ref.get(),data=snap.data()||{},a=access(data),devices={...(a.devices||{})},id=deviceId(),max=product.maxDevices||2,active=Object.values(devices).filter(v=>!v?.revoked).length;if(!devices[id]&&active>=max){state.access={...a,devices};dispatch('amc-device-limit',status());return status()}const fallback='iPhone '+Math.min(active+1,max),label=String(name||'').trim().slice(0,24)||fallback,now=firebase.firestore.FieldValue.serverTimestamp();devices[id]={...(devices[id]||{}),createdAt:devices[id]?.createdAt||now,lastSeenAt:now,label,revoked:false};await ref.set({email:state.user.email||'',accountState:data.accountState||'active',families:{[familyId]:{state:familyState(data),products:{[productId]:{...a,state:a.state||'active',devices,lastSeenAt:now}}}},lastSeenAt:now,updatedAt:now},{merge:true});state.access={...a,state:a.state||'active',devices};dispatch('amc-access-ready',status());return status()}async function signIn(e,p){if(!configured)throw new Error('Firebase is not configured.');return firebase.auth().signInWithEmailAndPassword(e,p)}async function signUp(e,p){if(!configured)throw new Error('Firebase is not configured.');const credential=await firebase.auth().createUserWithEmailAndPassword(e,p);await trackSignup();return credential}async function signOut(){if(configured)await firebase.auth().signOut()}async function revokeDevice(id){if(!state.user)throw new Error('Authentication required.');const db=firebase.firestore(),ref=db.collection('users').doc(state.user.uid),snap=await ref.get(),data=snap.data()||{},a=access(data),devices={...(a.devices||{})};if(devices[id])devices[id]={...devices[id],revoked:true,revokedAt:firebase.firestore.FieldValue.serverTimestamp()};await ref.set({families:{[familyId]:{products:{[productId]:{...a,devices}}}},updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return devices}window.AMCAccess={start,acceptLegal,registerDevice,signIn,signUp,signOut,revokeDevice,status,deviceId,trackSignupView,trackToolStart}})();
