(()=>{'use strict';
const $=id=>document.getElementById(id),cfg=window.AMC_FIREBASE_CONFIG||{},acfg=window.AMC_ACCESS_CONFIG||{},configured=Boolean(cfg.apiKey&&cfg.authDomain&&cfg.projectId&&cfg.appId);let db=null,current=[],view='overview';
const products=acfg.products||{tool:{label:'Acoustic M.C Tool',enabled:true,maxDevices:2}};
function setStatus(s){$('adminState').textContent=s}function fmt(v){try{const d=v?.toDate?v.toDate():v?new Date(v):null;return d&&!isNaN(d)?d.toLocaleString('ja-JP'):'—'}catch{return'—'}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function access(u,p){return u.products?.[p]||null}function activeDevices(a){return Object.values(a?.devices||{}).filter(x=>!x?.revoked).length}
function caution(a,p){const ds=Object.values(a?.devices||{});return ds.length>4||activeDevices(a)>(products[p]?.maxDevices||2)}
function rows(){const out=[];for(const u of current)for(const [p,meta]of Object.entries(products)){const a=access(u,p);if(!a)continue;if(view!=='overview'&&view!==p)continue;out.push({u,p,meta,a})}return out}
function render(){const q=$('search').value.trim().toLowerCase(),rs=rows().filter(x=>!q||(x.u.email||'').toLowerCase().includes(q)||x.u.id.toLowerCase().includes(q));$('controlTitle').textContent=view==='overview'?'ALL PRODUCTS':(products[view]?.label||view).toUpperCase();
$('totalUsers').textContent=new Set(rs.map(x=>x.u.id)).size;$('activeUsers').textContent=rs.filter(x=>(x.a.state||'active')==='active').length;$('cautionUsers').textContent=rs.filter(x=>caution(x.a,x.p)).length;$('bannedUsers').textContent=rs.filter(x=>x.a.state==='banned'||x.u.accountState==='banned').length;
$('users').innerHTML=rs.map(x=>{const s=x.u.accountState==='banned'?'banned':(x.a.state||'active');return '<tr><td>'+esc(x.u.email||'—')+'<small>'+esc(x.u.id)+'</small></td><td>'+esc(x.meta.label)+'</td><td>'+fmt(x.a.lastSeenAt)+'</td><td>'+activeDevices(x.a)+(caution(x.a,x.p)?' ⚠︎':'')+'</td><td><span class="state '+s+'">'+s.toUpperCase()+'</span></td><td><div class="actions"><button class="warn" data-state="suspended" data-id="'+x.u.id+'" data-p="'+x.p+'">一時停止</button><button class="danger" data-state="banned" data-id="'+x.u.id+'" data-p="'+x.p+'">BAN</button><button class="ok" data-state="active" data-id="'+x.u.id+'" data-p="'+x.p+'">解除</button></div></td></tr>'}).join('')||'<tr><td colspan="6" class="muted">対象ユーザーなし</td></tr>';document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>changeState(b.dataset.id,b.dataset.p,b.dataset.state))}
async function load(){setStatus('SYNC');const snap=await db.collection('users').orderBy('lastSeenAt','desc').limit(1000).get();current=snap.docs.map(d=>({id:d.id,...d.data()}));render();setStatus('ADMIN')}
async function changeState(id,p,state){if(!confirm((state==='banned'?'この製品でBANしますか？':state==='suspended'?'この製品を一時停止しますか？':'この製品をACTIVEへ戻しますか？')))return;const ref=db.collection('users').doc(id),snap=await ref.get(),u=snap.data()||{},a=u.products?.[p]||{};await ref.set({products:{[p]:{...a,state}},updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await load()}
async function init(){if(products.analyzer?.enabled)$('analyzerTab').hidden=false;if(!configured){$('loginStatus').textContent='Firebase設定が未接続です。firebase-config.js を設定してください。';setStatus('SETUP REQUIRED');return}firebase.initializeApp(cfg);db=firebase.firestore();await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);firebase.auth().onAuthStateChanged(async user=>{if(!user){$('loginPanel').hidden=false;$('console').hidden=true;setStatus('AUTH REQUIRED');return}const token=await user.getIdTokenResult(true);if(token.claims.admin!==true){$('loginStatus').textContent='このアカウントにはADMIN権限がありません。';await firebase.auth().signOut();return}$('loginPanel').hidden=true;$('console').hidden=false;await load()})}
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{view=b.dataset.product;document.querySelectorAll('[data-product]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});$('login').onclick=async()=>{try{$('loginStatus').textContent='';await firebase.auth().signInWithEmailAndPassword($('email').value.trim(),$('password').value)}catch(e){$('loginStatus').textContent=e.message}};$('logout').onclick=()=>firebase.auth().signOut();$('refresh').onclick=load;$('search').oninput=render;init()})();
