const startupSmoothing=smoothingOct;
const extrasTests=makeAction('RUN ADDITIONAL FIXES TESTS',async()=>{
  extrasTests.disabled=true;let savedRecord=null;const originalConfirm=window.confirm;
  const waitFor=async(fn,label)=>{for(let i=0;i<150;i++){if(fn())return;await delay(40);}throw Error('Timeout '+label);};
  try{
    pause(true);if(repeatEnabled)toggleRepeat();changePage('compare');
    assertTest(startupSmoothing===0,'new session MUSIC smoothing starts OFF');
    const blob=wav(8),bytes=await blob.arrayBuffer(),dv=new DataView(bytes);for(let i=44;i<bytes.byteLength;i+=2)dv.setInt16(i,dv.getInt16(i,true)*(i<bytes.byteLength/2?.5:1.5),true);
    await loadBlob('A',blob,'variable-A.wav');await loadBlob('B',new Blob([bytes],{type:'audio/wav'}),'variable-B.wav');setOffset(125);if(!gainEnabled)toggleGainMatch();await play('B');await delay(200);
    const state={ctx,transport,origin,A:slots.A,B:slots.B,offset,gain:gainResult,sr:ctx.sampleRate,channels:slots.B.buffer.numberOfChannels};
    let automations=0;const wrapped=[];
    for(const param of [transport.gain.gain,transport.matchGain.gain])for(const name of ['setValueAtTime','linearRampToValueAtTime','cancelScheduledValues','cancelAndHoldAtTime'])if(param[name]){const original=param[name];wrapped.push([param,name,original]);param[name]=function(...args){automations++;return original.apply(this,args);};}
    try{for(const [page,id]of [['listen','wave'],['compare','spectrum'],['diff','diffChart']]){changePage(page);expandCurrentPage();assertTest(fullGraph?.id===id,'layout-only fullscreen target '+page);const closed=new Promise(r=>$('graphDialog').addEventListener('close',r,{once:true}));$('graphDialog').close();await closed;}
      for(const value of ['0','0.16666666666666666','0.3333333333333333']){$('smoothing').value=value;$('smoothing').dispatchEvent(new Event('change'));}
      assertTest(ctx===state.ctx&&transport===state.transport&&origin===state.origin&&slots.A===state.A&&slots.B===state.B&&offset===state.offset&&gainResult===state.gain&&ctx.sampleRate===state.sr&&slots.B.buffer.numberOfChannels===state.channels,'fullscreen/return/smoothing preserve exact audio context, graph, gains, clock, channels and sample rate');
      assertTest(automations===0,'fullscreen and smoothing schedule no gain/fade automation');
    }finally{for(const [param,name,original]of wrapped)param[name]=original;}
    pause();if(gainEnabled)toggleGainMatch();setOffset(0);$('freqMode').value='music';$('smoothing').value='0';$('smoothing').dispatchEvent(new Event('change'));changePage('diff');cursor=1;await play('A');await delay(180);await sampleVisual();drawDiff();
    const first=currentDifferences(diffSources().a,diffSources().b).find(r=>r.delta< -5);assertTest(diffSources().live&&first&&$('diffMessage').textContent.includes('現在位置'),'DIFF uses aligned current FFT with negative first-half difference');
    $('seek').value=5;$('seek').dispatchEvent(new Event('input'));await delay(220);await sampleVisual();drawDiff();assertTest(diffSources().live&&currentDifferences(diffSources().a,diffSources().b).some(r=>r.delta>3),'DIFF follows SEEK into positive second-half difference');
    $('smoothing').value=String(1/3);$('smoothing').dispatchEvent(new Event('change'));assertTest($('diffMessage').textContent.includes('Smoothing 1/3 Oct'),'DIFF numbers and graph immediately receive smoothing');
    if(gainEnabled)toggleGainMatch();drawDiff();assertTest($('diffMessage').textContent.includes('GAIN MATCH OFF · 原音差'),'DIFF explicitly shows Gain Match OFF');toggleGainMatch();drawDiff();assertTest($('diffMessage').textContent.includes('GAIN MATCH ON')&&$('diffMessage').textContent.includes('A ')&&$('diffMessage').textContent.includes('B '),'DIFF explicitly shows Gain Match ON and both applied offsets');
    $('freqMode').value='standard';updateWorkspace();draw();assertTest($('smoothing').disabled&&$('diffMessage').textContent.includes('固定'),'STANDARD remains fixed 1/3 independent of MUSIC setting');pause();drawDiff();assertTest($('diffMessage').textContent.includes('全体平均'),'paused DIFF explicitly labels whole-source average');
    const repeatBytes=await wav(2).arrayBuffer(),repeatView=new DataView(repeatBytes);for(let i=44;i<repeatBytes.byteLength;i+=2)repeatView.setInt16(i,repeatView.getInt16(i,true)*2,true);
    await loadBlob('A',wav(2),'repeat-A.wav');await loadBlob('B',new Blob([repeatBytes],{type:'audio/wav'}),'repeat-B.wav','air');setOffset(-125);if(!gainEnabled)toggleGainMatch();toggleRepeat();const g=gainResult,c=ctx;await play('B');await delay(2250);
    assertTest(playing==='B'&&position()<1&&offset===-.125&&gainEnabled&&gainResult===g&&ctx===c,'REPEAT wraps common interval preserving side, negative sync, gain and context');
    assertTest(gainResult.mode==='air'&&transport.matchGain.gain.value<1,'REPEAT retains active AIR gain attenuation, not just ON label');
    assertTest($('repeatToggle').getAttribute('aria-pressed')==='true'&&$('fullRepeat').getAttribute('aria-pressed')==='true','normal and fullscreen REPEAT state synchronized');toggleRepeat();await delay(2200);assertTest(!playing&&position()===limits()[0],'REPEAT OFF stops normally at common end');
    toggleRepeat();await play('A');finishPlayback();pause(true);await delay(150);assertTest(!playing,'explicit STOP cancels pending repeat restart');toggleRepeat();
    changePage('listen');for(const id of ['pause','stop']){const r=$(id).getBoundingClientRect();assertTest(r.width>=44&&r.width<=46&&r.height>=44,id+' compact width retains 44px touch area');}
    for(const [page,topic]of [['listen','LISTEN'],['compare','COMPARE'],['diff','DIFF'],['history','MEMO']]){changePage(page);document.querySelector('.top .help-button').click();assertTest($('helpDialog').querySelector('h2').textContent===topic,'page help directly opens '+topic);$('helpDialog').close();await delay(20);}
    showHelp('GAIN MATCH');$('helpDialog').querySelector('.dialog-body > button').click();assertTest(helpTrail.at(-1).details,'help navigates to specifications rather than ABOUT top');const term=[...$('helpDialog').querySelectorAll('.term-link')].find(b=>b.textContent==='K-weighting');term.click();assertTest($('helpDialog').querySelector('h2').textContent==='K-weighting'&&$('helpDialog').textContent.includes('聴く音'),'term link opens beginner explanation');$('helpDialog').querySelector('.dialog-body > button').click();assertTest(helpTrail.at(-1).topic==='GAIN MATCH','help Back restores parent without browser history');$('helpDialog').close();await delay(20);
    changePage('history');assertTest(!document.querySelector('[data-panel=history] [data-memo=reference]')&&!document.querySelector('[data-panel=history] #referenceCard')&&!!$('saveReference'),'MEMO removes REFERENCE only; AIR SAVE REFERENCE retained');
    assertTest($('cameraPhotoInput').getAttribute('capture')==='environment'&&$('cameraPhotoInput').accept==='image/*'&&!$('libraryPhotoInput').hasAttribute('capture'),'separate photo camera and library picker semantics');
    const canvas=document.createElement('canvas');canvas.width=canvas.height=8;canvas.getContext('2d').fillRect(0,0,8,8);const png=await new Promise(r=>canvas.toBlob(r));const file=new File([png],'test-photo.png',{type:'image/png'}),data=new DataTransfer();data.items.add(file);$('cameraPhotoInput').files=data.files;await $('cameraPhotoInput').onchange({target:$('cameraPhotoInput')});
    const lib=new DataTransfer();lib.items.add(new File([png],'library-photo.png',{type:'image/png'}));$('libraryPhotoInput').files=lib.files;await $('libraryPhotoInput').onchange({target:$('libraryPhotoInput')});assertTest(memoPhotos.draft.length===2,'camera/library File handlers add photos to same memo draft');
    $('featureA').value='A tighter low end';$('featureB').value='B wider image';$('memo').value='TEST speaker moved 10cm';$('memo').dispatchEvent(new Event('input'));savedRecord=await saveMemoRecord();assertTest(savedRecord?.featureA.includes('tighter')&&savedRecord?.featureB.includes('wider')&&savedRecord?.memo.includes('10cm')&&savedRecord.photos.length===2&&memoPhotos.draft.length===0,'A/B characteristics, memo, timestamp and photos commit atomically');
    memoPhotos.db.close();memoPhotos.db=null;await openMemoRecord(savedRecord);await waitFor(()=>$('memoRecordDialog').querySelectorAll('img').length===2,'photo reload');assertTest($('memoRecordDialog').textContent.includes('A tighter low end')&&$('memoRecordDialog').textContent.includes('B wider image')&&$('memoRecordDialog').textContent.includes('10cm'),'saved record reopens A/B characteristics and memo from IndexedDB without replacing session fields');await waitFor(()=>[...$('memoRecordDialog').querySelectorAll('img')].every(img=>img.complete&&img.naturalWidth===8),'photo decode');assertTest(true,'stored photos decode through local blob CSP');const photoClosed=new Promise(resolve=>$('memoRecordDialog').addEventListener('close',resolve,{once:true}));$('memoRecordDialog').close();await photoClosed;assertTest(memoPhotos.viewUrls.length===0,'closing photo viewer releases image URLs');
    window.confirm=()=>true;const pick=new DataTransfer();pick.items.add(new File([wav(1)],'input-only.wav',{type:'audio/wav'}));$('fileA').files=pick.files;const p=$('fileA').oninput({target:$('fileA'),type:'input'}),q=$('fileA').onchange({target:$('fileA'),type:'change'});assertTest(p===q,'input/change picker events share one import');await p;assertTest(slots.A.name==='input-only.wav'&&inputEvents.some(e=>e.event==='picker input'),'input event supported and actual File metadata recorded locally');
    const faulty=new Blob(['abc']);faulty.arrayBuffer=()=>Promise.reject(new DOMException('provider read error','NotReadableError'));assertTest(new TextDecoder().decode(await readMediaBytes(faulty))==='abc','provider ArrayBuffer failure can use FileReader fallback');
    log('ADDITIONAL FIXES TESTS COMPLETE');
  }catch(error){log('FAIL '+error.stack);}finally{window.confirm=originalConfirm;pause();if(repeatEnabled)toggleRepeat();extrasTests.disabled=false;if(savedRecord){const db=await memoDB();await memoTransaction(db,['records','photos'],'readwrite',tx=>{tx.objectStore('records').delete(savedRecord.id);for(const p of savedRecord.photos)tx.objectStore('photos').delete(p.key);});await listMemoRecords();}}
});testBox.append(extrasTests);
