import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const c=vm.createContext({Blob});
vm.runInContext(readFileSync(new URL('../media-input.js',import.meta.url),'utf8'),c);
const atom=(type,...parts)=>c.atomBytes(type,parts),u32=(...values)=>{const b=new Uint8Array(values.length*4),v=new DataView(b.buffer);values.forEach((n,i)=>v.setUint32(i*4,n));return b;};
const track=(kind,offset=8)=>atom('trak',atom('mdia',atom('hdlr',u32(0,0),Uint8Array.from(kind,x=>x.charCodeAt(0))),atom('minf',atom('stbl',atom('stsd',u32(0,1),atom('mp4a',u32(0,0))),atom('stsz',u32(0,4,2)),atom('stsc',u32(0,1,1,2,1)),atom('stco',u32(0,1,offset))))));
const make=(tracks=[track('vide'),track('soun')],extra=[])=>new Blob([atom('mdat',u32(123,456)),atom('moov',atom('mvhd',u32(0)),...tracks,...extra)],{type:'video/quicktime'});
let count=0;const check=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
await check('empty picker payload fails explicitly',()=>assert.rejects(c.inspectMediaInput(new Blob([]),'IMG.MOV'),/空/));
await check('audio WebM AIR REC never gets video UI',async()=>assert.equal((await c.inspectMediaInput(new Blob(['audio'],{type:'audio/webm;codecs=opus'}),'AIR_REC.webm')).isVideo,false));
await check('empty MIME MOV detected by track bytes and remuxed',async()=>{const b=new Blob([make()]),r=await c.inspectMediaInput(b,'IMG_0001.MOV');assert.equal(r.path,'audio-track-remux');assert.equal(r.isVideo,true);const a=await c.inspectMediaInput(r.audioBlob,'audio.m4a');assert.equal(a.isVideo,false);assert.equal(b.size,make().size);});
await check('audio-only MP4 does not show video even with video MIME',async()=>assert.equal((await c.inspectMediaInput(make([track('soun')]),'audio.mp4')).isVideo,false));
await check('no audio track preserves prior slot through rejection',()=>assert.rejects(c.inspectMediaInput(make([track('vide')]),'silent.mov'),/音声トラックがありません/));
await check('multiple audio tracks never silently select one',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),track('soun'),track('soun')]),'multi.mov'),/複数/));
await check('fragmented input explicitly uses native decoder',async()=>assert.equal((await c.inspectMediaInput(make(undefined,[atom('mvex',u32(0))]),'fragment.mp4')).path,'native-container'));
await check('out-of-bounds chunk references rejected',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),track('soun',999999)])),/参照先/));
await check('truncated container rejected',()=>assert.rejects(c.inspectMediaInput(make().slice(0,25),'broken.mov'),/サイズ情報/));
await check('unmodified WAV uses native path',async()=>{const b=new Blob(['RIFF1234WAVE'],{type:'audio/wav'});assert.equal((await c.inspectMediaInput(b,'test.wav')).audioBlob,b);});
console.log(`${count} media-input tests passed`);
