import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const c=vm.createContext({Blob});
vm.runInContext(readFileSync(new URL('../media-input.js',import.meta.url),'utf8'),c);
const atom=(type,...parts)=>c.atomBytes(type,parts),u32=(...values)=>{const b=new Uint8Array(values.length*4),v=new DataView(b.buffer);values.forEach((n,i)=>v.setUint32(i*4,n));return b;};
const track=(kind,offset=8)=>atom('trak',atom('mdia',atom('hdlr',u32(0,0),Uint8Array.from(kind,x=>x.charCodeAt(0))),atom('minf',atom('stbl',atom('stsd',u32(0,1),atom('mp4a',u32(0,0))),atom('stsz',u32(0,4,2)),atom('stsc',u32(0,1,1,2,1)),atom('stco',u32(0,1,offset))))));
const make=(tracks=[track('vide'),track('soun')],extra=[])=>new Blob([atom('mdat',u32(123,456)),atom('moov',atom('mvhd',u32(0)),...tracks,...extra)],{type:'video/quicktime'});
let count=0;const check=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
await check('empty picker payload fails explicitly',()=>assert.rejects(c.inspectMediaInput(new Blob([]),'IMG.MOV'),/空/));
await check('audio WebM AIR REC never gets video UI',async()=>assert.equal((await c.inspectMediaInput(new Blob(['audio'],{type:'audio/webm;codecs=opus'}),'AIR_REC.webm')).isVideo,false));
await check('empty MIME MOV detected by track bytes and remuxed',async()=>{const b=new Blob([make()]),r=await c.inspectMediaInput(b,'IMG_0001.MOV');assert.equal(r.path,'audio-track-remux');assert.equal(r.isVideo,true);const a=await c.inspectMediaInput(r.audioBlob,'audio.m4a');assert.equal(a.isVideo,false);assert.equal(b.size,make().size);});
await check('audio-only MP4 does not show video even with video MIME',async()=>assert.equal((await c.inspectMediaInput(make([track('soun')]),'audio.mp4')).isVideo,false));
await check('no audio track preserves prior slot through rejection',()=>assert.rejects(c.inspectMediaInput(make([track('vide')]),'silent.mov'),/音声トラックがありません/));
await check('multiple audio tracks never silently select one',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),track('soun'),track('soun')]),'multi.mov'),/複数/));
await check('fragmented input explicitly uses native decoder',async()=>assert.equal((await c.inspectMediaInput(make(undefined,[atom('mvex',u32(0))]),'fragment.mp4')).path,'native-container'));
await check('out-of-bounds chunk references rejected',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),track('soun',999999)])),/参照先/));
await check('truncated container rejected',()=>assert.rejects(c.inspectMediaInput(make().slice(0,25),'broken.mov'),/サイズ情報/));
await check('unmodified WAV uses native path',async()=>{const b=new Blob(['RIFF1234WAVE'],{type:'audio/wav'});assert.equal((await c.inspectMediaInput(b,'test.wav')).audioBlob,b);});
function alternate(id,group,enabled,{version=0,codec='mp4a',ref=false}={}){
  const header=new Uint8Array(version?96:84),v=new DataView(header.buffer);header[0]=version;header[3]=enabled?1:0;v.setUint32(version?20:12,id);v.setUint16(version?46:34,group);
  const data=track('soun'),index=Array.from(data).findIndex((_,i)=>String.fromCharCode(...data.slice(i,i+4))==='mp4a');data.set(Uint8Array.from(codec,x=>x.charCodeAt(0)),index);
  return atom('trak',atom('tkhd',header),...(ref?[atom('tref',atom('fall',u32(99)))]:[]),data.slice(8));
}
await check('TN3177 enabled AAC chosen regardless of serialized order',async()=>{for(const tracks of [[alternate(7,3,true,{ref:true}),alternate(9,3,false,{codec:'apac'})],[alternate(9,3,false,{codec:'apac'}),alternate(7,3,true,{ref:true})]]){const r=await c.inspectMediaInput(make([track('vide'),...tracks]));assert.equal(r.selectedTrackId,7);assert.equal(r.selection,'enabled-alternate');assert.ok(r.notice.includes('7'));const bytes=new Uint8Array(await r.audioBlob.arrayBuffer());assert.ok(!new TextDecoder().decode(bytes).includes('tref'));assert.equal((await c.inspectMediaInput(r.audioBlob)).isVideo,false);}});
await check('version 1 track header default selection',async()=>{const r=await c.inspectMediaInput(make([track('vide'),alternate(9,3,false,{version:1,codec:'apac'}),alternate(7,3,true,{version:1})]));assert.equal(r.selectedTrackId,7);});
await check('ambiguous defaults/groups/ids are not guessed',async()=>{for(const tracks of [[alternate(1,0,true),alternate(2,0,false)],[alternate(1,1,true),alternate(2,2,false)],[alternate(1,1,true),alternate(2,1,true)],[alternate(1,1,false),alternate(2,1,false)],[alternate(1,1,true),alternate(1,1,false)]])await assert.rejects(c.inspectMediaInput(make([track('vide'),...tracks])),/既定選択/);});
await check('unsupported enabled codec never silently chooses disabled AAC',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),alternate(1,1,true,{codec:'apac'}),alternate(2,1,false)])),/単独抽出/));
await check('fragmented multitrack does not use ambiguous native-container fallback',()=>assert.rejects(c.inspectMediaInput(make([track('vide'),alternate(1,1,true),alternate(2,1,false)],[atom('mvex',u32(0))])),/単独抽出/));
console.log(`${count} media-input tests passed`);
